name: Code Quality Check

# Controls when the workflow will run
on:
  # Triggers the workflow on push to every branch or pull request events but only for the "main" branch
  push:
    branches: '**'
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ktlint:
    name: Ktlint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          android: true
          fail_on_error: true
          level: warning

  detekt:
    name: Detekt Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: alaegin/Detekt-Action@v1.22.0
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: detekt-config.yml # Change config path
